### ISSUE TITLE
buckets work in claims that are owned by other users

### ISSUE THREAD

**Issue by Rionlion100** [Draylar/get-off-my-lawn#1]

**Comment by Draylar** [comment]
Should be fixed via [BucketItemMixin](https://github.com/Draylar/get-off-my-lawn/blob/master/src/main/java/draylar/goml/mixin/BucketItemMixin.java). It seems like `UseBlockCallback` doesn't work well with buckets on the client, which was leading to desync (the water doesn't actually "disappear," but just goes away until a relog).

 I'd like to patch up the `rayTrace` method I copied from `Item`, but for now, this should be good enough.

Also tested and confirmed this fixes _placing_ ghost fluids. Thanks for the report!
