### ISSUE TITLE
Allow ops to edit inside claim

### ISSUE THREAD

**Issue by PastMoments** [Draylar/get-off-my-lawn#10]
Currently, even ops cannot modify things in claims, which is a bit of an issue in servers.

**Comment by hYdos** [comment]
no :)

**Comment by hYdos** [comment]
@Draylar wuts ur opinion on this? ops could abuse this so idk

**Comment by Draylar** [comment]
If your OP is abusing it, they probably shouldn't be OP, lol.

Will definitely get this out with the next permissions update.

**Comment by Draylar** [comment]
Done in 1.2.0 beta.
