### ISSUE TITLE
Death chests inside claims cannot be claimed

### ISSUE THREAD

**Issue by Draylar** [Draylar/get-off-my-lawn#22]
![image](https://user-images.githubusercontent.com/17728338/103497405-088b0c00-4e07-11eb-9da7-4e6f530f4c78.png)

**Comment by dandin87** [comment]
Just wanted to bring this up again. death chests location are stored in /world/data/vanilladeathchest.dat in case that helps at all. Also linking the AoF3 NA server vanilladeathchest.dat file in discord

**Comment by dandin87** [comment]
Or perhaps simply allow anything with this tab to be interactable -> [TAG_String] "CustomName": "{"text":"Death Chest"}"
/tellme looking-at to-chat
Chest (minecraft:chest) has a BlockEntity
Full block state: Block{minecraft:chest}[facing=south,type=right,waterlogged=false]
Hardness: 2.5000, Explosion resistance: 2.5000, Material: WOOD
Block class: net.minecraft.class_2281
BlockState properties:
class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, south, west, east]}: south
class_2754{name=type, clazz=class net.minecraft.class_2745, values=[SINGLE, LEFT, RIGHT]}: RIGHT
class_2746{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]}: false
BlockEntity class: net.minecraft.class_2595

BlockEntity NBT (from BlockEntity::write()):
[TAG_Compound (6 values)] 
{
    [TAG_String] "CustomName": "{"text":"Death Chest"}"
    [TAG_List (0 values of type ?)] "Items"
    [
    ]
    [TAG_String] "id": "minecraft:chest"
    [TAG_Int] "x": 737
    [TAG_Int] "y": 179
    [TAG_Int] "z": -2273
}

**Comment by Draylar** [comment]
Wait, Death Chests have tags like that on them? That makes this easier. I'll look into it.
