### ISSUE TITLE
perma-flight after breaking flight augment

### ISSUE THREAD

**Issue by superon** [Draylar/get-off-my-lawn#26]
seems very much like after placing the flight augment, breaking it gives the player the ability to fly whenever they please wherever they please.
this appears to be the case too when placing a flight augment then upgrading the claim size.

also seems that the flight augment only activates after a player has left and re-entered the claim it's attached to

**Comment by Draylar** [comment]
Fixed in 1.3.2 beta, thank you for the report~

**Comment by superon** [comment]
regarding 1.3.2 beta
here's another way to gain flight outside the confines of a claim..
place and anchor with flight augment on top.
place an end crystal next to the augment and blow it up.
relog and harvest the claim anchor.
fly anywhere :/ posted here so i'm not double posting, hope that's good
