### ISSUE TITLE
Server side port-thingy

### ISSUE THREAD

**Issue by Patbox** [Draylar/get-off-my-lawn#50]
Hello! I'm interested in making and releasing "port"/modification of this mod as server side one (still fabric) with usage of my own Polymer library. However I want to ask if you would be okay with me publishing it on Curseforge/Modrinth. While I know that license allows this, I prefer to still ask just to be fair with you.

**Comment by Draylar** [comment]
Of course, feel free! Let me know if/once you've uploaded anything - would love to see how it ends up working! Good luck with the project.

**Comment by Patbox** [comment]
Started working on it, currently it's only on github https://github.com/Patbox/get-off-my-lawn-server-sided
For now it's just server port + 1.18 support + some fixes for bugs I've found. I plan to exdend it more in a future through
